package metacase.https.bpoclientswebservice_metacase;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BpoClientsWebService", 
targetNamespace = "https://BpoClientsWebService.metacase.eu/", 
wsdlLocation = "file:ClientService.wsdl")
public class BpoClientsWebService
    extends Service
{

    private final static URL BPOCLIENTSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BPOCLIENTSWEBSERVICE_EXCEPTION;
    private final static QName BPOCLIENTSWEBSERVICE_QNAME = new QName("https://BpoClientsWebService.metacase.eu/", "BpoClientsWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:ClientService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPOCLIENTSWEBSERVICE_WSDL_LOCATION = url;
        BPOCLIENTSWEBSERVICE_EXCEPTION = e;
    }

    public BpoClientsWebService() {
        super(__getWsdlLocation(), BPOCLIENTSWEBSERVICE_QNAME);
    }

    public BpoClientsWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPOCLIENTSWEBSERVICE_QNAME, features);
    }

    public BpoClientsWebService(URL wsdlLocation) {
        super(wsdlLocation, BPOCLIENTSWEBSERVICE_QNAME);
    }

    public BpoClientsWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPOCLIENTSWEBSERVICE_QNAME, features);
    }

    public BpoClientsWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpoClientsWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BpoClientsWebServiceSoap
     */
    @WebEndpoint(name = "BpoClientsWebServiceSoap")
    public BpoClientsWebServiceSoap getBpoClientsWebServiceSoap() {
        return super.getPort(new QName("https://BpoClientsWebService.metacase.eu/", "BpoClientsWebServiceSoap"), BpoClientsWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpoClientsWebServiceSoap
     */
    @WebEndpoint(name = "BpoClientsWebServiceSoap")
    public BpoClientsWebServiceSoap getBpoClientsWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://BpoClientsWebService.metacase.eu/", "BpoClientsWebServiceSoap"), BpoClientsWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPOCLIENTSWEBSERVICE_EXCEPTION!= null) {
            throw BPOCLIENTSWEBSERVICE_EXCEPTION;
        }
        return BPOCLIENTSWEBSERVICE_WSDL_LOCATION;
    }

}
