package metacase.https.bpoclientswebservice_metacase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BpoClientsWebServiceSoap", targetNamespace = "https://BpoClientsWebService.metacase.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BpoClientsWebServiceSoap {


    /**
     * 
     * @param dataInput
     * @return
     *     returns https.bpoclientswebservice_metacase.SenderDataResponse
     */
    @WebMethod(operationName = "ReceiveDataFromClient", action = "https://BpoClientsWebService.metacase.eu/ReceiveDataFromClient")
    @WebResult(name = "ReceiveDataFromClientResult", targetNamespace = "https://BpoClientsWebService.metacase.eu/")
    @RequestWrapper(localName = "ReceiveDataFromClient", targetNamespace = "https://BpoClientsWebService.metacase.eu/", className = "https.bpoclientswebservice_metacase.ReceiveDataFromClient")
    @ResponseWrapper(localName = "ReceiveDataFromClientResponse", targetNamespace = "https://BpoClientsWebService.metacase.eu/", className = "https.bpoclientswebservice_metacase.ReceiveDataFromClientResponse")
    public SenderDataResponse receiveDataFromClient(
        @WebParam(name = "dataInput", targetNamespace = "https://BpoClientsWebService.metacase.eu/")
        SenderDataInformation dataInput);

}
